### ISSUE TITLE
Is it possible to run this as part of `mix test`?

### ISSUE THREAD

**Issue by axelson** [evnu/docception#1]
Hi, thanks for this library!

Is it possible to run this as part of `mix test`?

**Comment by evnu** [comment]
The simplest solution would be to use an alias for `test` in your `mix.exs`. That alias should then call the `test` task as well as `docception`. With that, both will be called on `mix test`. See the example directory (the alias should be extended to run `mix test` of course).

**Comment by axelson** [comment]
Ah, ok. That makes sense as an approach.
