### ISSUE TITLE
Maybe deprecate this library in favor of ExUnit.DocTest.doctest_file/2?

### ISSUE THREAD

**Issue by axelson** [evnu/docception#11]
In Elixir 1.15 [`ExUnit.DocTest.doctest_file/2`](https://hexdocs.pm/ex_unit/1.15/ExUnit.DocTest.html#doctest_file/2) was added which allows you to easily doctest an arbitrary markdown file. I think that updating the readme of this project to point to ExUnit.DocTest.doctest_file/2` will help people find the new function.

Although if you have plans that extend beyond what `ExUnit.DocTest.doctest_file/2` then of course there's no need to deprecate the library!

**Comment by evnu** [comment]
Thanks, I will look into that function! Hopefully, it can be used as a simple alias, then I will archive this repository and add a note to use that function :)

**Comment by evnu** [comment]
Well, can't use an alias (as `doctest_file/1,2` is a macro generating functions, similar to what docception did, but doing this at compile time), so it cannot be used in a function. But, a `for` comprehension can be used to generate a bunch of such macro calls, see #12.
